# Generated by Django 4.2.7 on 2025-12-31 11:02

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FaceImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255, unique=True)),
                ("original_filename", models.CharField(max_length=255)),
                ("file", models.ImageField(upload_to=core.models.get_upload_path)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to=core.models.get_upload_path
                    ),
                ),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("face_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="face_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "face_images",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InputVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255, unique=True)),
                ("original_filename", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to=core.models.get_upload_path)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to=core.models.get_upload_path
                    ),
                ),
                (
                    "duration",
                    models.FloatField(
                        blank=True, help_text="Duration in seconds", null=True
                    ),
                ),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("fps", models.FloatField(blank=True, null=True)),
                ("codec", models.CharField(blank=True, max_length=50)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="input_videos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "input_videos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OutputVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255, unique=True)),
                ("file", models.FileField(upload_to=core.models.get_upload_path)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to=core.models.get_upload_path
                    ),
                ),
                ("duration", models.FloatField(blank=True, null=True)),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("fps", models.FloatField(blank=True, null=True)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                (
                    "processing_method",
                    models.CharField(
                        choices=[
                            ("traditional", "Traditional"),
                            ("inswapper", "Inswapper"),
                        ],
                        default="inswapper",
                        max_length=20,
                    ),
                ),
                (
                    "processing_time",
                    models.FloatField(
                        blank=True, help_text="Processing time in seconds", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "progress",
                    models.IntegerField(default=0, help_text="Progress 0-100"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "face_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outputs",
                        to="core.faceimage",
                    ),
                ),
                (
                    "input_video",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outputs",
                        to="core.inputvideo",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="output_videos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "output_videos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("config_key", models.CharField(max_length=100, unique=True)),
                ("config_value", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "system_config",
                "indexes": [
                    models.Index(
                        fields=["config_key"], name="system_conf_config__c467d4_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProcessingTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("video", "Video Processing"),
                            ("camera", "Camera Processing"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(default=0, help_text="Progress 0-100"),
                ),
                ("error_message", models.TextField(blank=True)),
                ("processing_params", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "face_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="core.faceimage",
                    ),
                ),
                (
                    "input_video",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="core.inputvideo",
                    ),
                ),
                (
                    "output_video",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task",
                        to="core.outputvideo",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "processing_tasks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="processing__user_id_854b79_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="processing__created_4110a7_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="outputvideo",
            index=models.Index(
                fields=["user", "status"], name="output_vide_user_id_0d9cae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="outputvideo",
            index=models.Index(
                fields=["-created_at"], name="output_vide_created_883e4e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inputvideo",
            index=models.Index(
                fields=["user", "is_active"], name="input_video_user_id_21e7a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inputvideo",
            index=models.Index(
                fields=["-created_at"], name="input_video_created_29d93b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="faceimage",
            index=models.Index(
                fields=["user", "is_active"], name="face_images_user_id_d2fd21_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="faceimage",
            index=models.Index(
                fields=["-created_at"], name="face_images_created_2d0647_idx"
            ),
        ),
    ]
