# Generated by Django 4.2.7 on 2025-12-31 13:53

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="faceimage",
            name="local_path",
            field=models.CharField(
                blank=True, help_text="本地文件系统路径", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="inputvideo",
            name="local_path",
            field=models.CharField(
                blank=True, help_text="本地文件系统路径", max_length=500, null=True
            ),
        ),
        migrations.AlterField(
            model_name="faceimage",
            name="file",
            field=models.ImageField(
                blank=True, null=True, upload_to=core.models.get_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="inputvideo",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=core.models.get_upload_path
            ),
        ),
    ]
